# Generated by Django 3.1.8 on 2021-04-16 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lockers', '0003_personalqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalqr',
            name='recipient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalqr',
            name='uuid',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='qr',
            name='uuid',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
